import { type NextPage } from "next";
import Head from "next/head";
import { useSession } from "next-auth/react";

import LoggedIn from "~/components/LoggedIn";
import LoggedOut from "~/components/LoggedOut";

const Home: NextPage = () => {
  const { data: sessionData } = useSession();

  return (
    <>
      <Head>
        <title>Timeliner</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
          <h1 className="text-5xl font-extrabold tracking-tight text-white sm:text-[5rem]">
            Timeliner
          </h1>

          <div className="flex flex-col items-center gap-2">
            {sessionData && <LoggedIn />}
            {!sessionData && <LoggedOut />}
          </div>
        </div>
      </main>
    </>
  );
};

export default Home;
